# Chapter 6 객체지향 프로그래밍
> 소프트웨어 공학의 목적은 복잡도를 생성하는 게 아니라 복잡도를 제어하는 것이다.  
-파멜라 제이브

객체지향 프로그래밍은 오늘날 인기 있는 프로그래밍 패러다임의 하나입니다. 올바르게 사용하면 절차적 프로그래밍 등에 비해 많은 장점이 있습니다. 많은 경우 객체지향 프로그래밍은 금융 모델링이나 금융 알고리즘 구현에 아주 적합합니다. 그러나 객체지향 프로그래밍의 일부 속성이나 패러다임 전반에 대한 비판도 만만치 않습니다. 이번 장에서는 중립적인 관점에서 객체지향 프로그래밍이 금융 분야의 프로그래머나 퀀트가 사용할 수 있는 중요한 도구라는 점을 설명합니다. 객체지향 프로그래밍을 하려면 몇 가지 용어를 알아야 합니다. 이 장에서 중요한 용어들은 다음과 같습니다.  
* 클래스: 일련의 객체에 대한 추상적 정의
* 객체: 클래스에 속하는 하나의 대상
* 속성: 클래스나 클래스의 객체가 가지고 있는 특징. 클래스면 클래스 속성, 객체면 객체 속성이라고 합니다.
* 메서드: 클래스가 구현할 수 있는 연산.
* 인수: 메서드가 받아들이는 값으로 실행에 영향을 미칩니다.
* 객체화: 추상 클래스에 기반해서 특정 객체를 생성하는 작업.  

객체지향 프로그래밍은 인간에 친화적인 몇 가지 특성이 있습니다.  
* 자연스러운 사고방식: 인간이 자동차나 금융 상품과 같은 현실세계의 객체 혹은 추상적인 객체에 대해 생각하는 것과 유사하므로 이러한 객체의 특성을 모델링할 때 적합합니다.
* 복잡도 감소: 특성을 하나하나 모델링하므로 문제나 알고리즘의 복잡도를 줄이는 데 도움이 됩니다.
* 더 나은 사용자 인터페이스: 대체로 더 나은 사용자 인터페이스와 더 간결한 코드를 제공합니다.
* 파이썬스러운 모델링 방법: 프로그래머가 표준 파이썬 클래스와 비슷하게 동작하는 사용자 정의 클래스를 만들 수 있게 합니다.  

다음은 객체지향 프로그래밍의 몇 가지 기술적 특성입니다.
* 추상화: 속성과 메서드를 사용하면 필요한 것에만 초점을 맞추어 추상적이고 유연한 모델을 만들 수 있습니다. 금융에서는 추상적인 방법으로 금융 상품을 모델링하는 클래스를 만들 수 있습니다. 이러한 클래스의 객체들은 구체적인 금융 상품이 되어 투자 은행에서 가공하고 판매할 수 있습니다.
* 모듈화: 객체지향 프로그래밍은 코드를 여러 개의 모듈로 나누고 이를 연결하여 전체 모드를 구성할 수 있습니다. 예를 들어 주식을 기초 자산으로 하는 유러피안 옵션을 하나의 클래스로 만들 수도 있지만 기초 자산과 그 기초 자산에 기반하는 옵션, 이렇게 두 개 클래스로 나눌 수도 있습니다.
* 상속: 상속은 하나의 클래스가 가진 속성과 메서드를 다른 클래스에 전달하는 것을 말합니다. 금융에서는 일반적인 금융 상품에서 시작하여 일반적인 파생상품, 유러피안 옵션, 유러피안 콜 옵션 순으로 상속받을 수 있습니다. 모든 클래스는 부모 클래스의 속성과 메서드를 이어받습니다.
* 집합화(aggregation): 독립적으로 존재할 수 있는 여러 개의 객체를 모아 하나의 객체로 만드는 것을 말합니다. 유러피안 콜 옵션은 기초 자산이 되는 주식이나 관련된 단기 할인 이자율 등을 속성으로 가질 수 있습니다. 주식과 단기 이자율 속성은 물론 다른 객체에 의해서도 독립적으로 사용될 수 있습니다.
* 합성화(composition): 집합화와 비슷하지만 각 객체가 독립적으로 존재할 수는 없습니다. 예를 들어 고정금리 현금흐름(fixed leg)과 변동금리 현금흐름(floating leg)을 가진 고객 맞춤형 이자율 스왑을 생각해봅시다. 이 두 개의 현금흐름은 스왑이라는 상품을 떠나서는 독립적으로 존재할 수 없습니다.
* 다형성(polymorphism): 다형성은 여러 가지 형태로 나타납니다. 파이썬에서는 덕 파이핑(duck typing)이라 불리는 형태로 나타나는데, 이는 표준 연산이 어떤 객체를 다루고 있는지 정확히 알지 못하더라도 여러 가지 클래스와 객체에서 구현될 수 있음을 의미합니다. 예를 들어 금융 상품 클래에서 객체(주식, 옵션, 스왑)의 구체적인 자료형을 몰라도 `get_current_price()`라는 메서드를 호출할 수 있습니다.
* 캡슐화: 이 개념은 클래스 내부에서 데이터를 만들고 퍼블릭 메서드에 의해서만 접근할 수 있는 방식을 말합니다. 주식을 모델링하는 클래스는 `current_stock_price`라는 속성을 가질 수 있습니다. 캡슐화를 하면 이 값은 `get_current_stock_price()` 메서드를 통해서만 얻을 수 있고 값 자체에 사용자가 바로 접근할 수는 없습니다. 이러한 방식을 사용하면 속성값을 의도치 않게 바꾸는 실수를 막을 수 있습니다. 하지만 파이썬 클래스에서는 데이터를 숨기는 데 제한이 있습니다. 

이러한 특징들은 다음과 같이 두 가지 소프트웨어 엔지니어링 목표로 요약할 수 있습니다.
* 재사용성: 상속과 다형성은 코드의 재사용성을 향상시키고 개발의 효율성과 프로그래머의 생산성을 증가시킵니다. 코드 관리도 단순해집니다.
* 중복 방지: 동시에 중복이 거의 없는 코드를 작성할 수 있습니다. 반복되는 코드 작성을 피하고 디버깅과 테스트에 들어가는 노력을 덜 수 있을 뿐만 아니라 전체 코드의 양도 감소합니다.

이 장은 다음과 같이 구성됩니다.
* 파이썬 객체 소개: 객체지향 프로그래밍 관점에서 파이썬 객체 소개
* 파이썬 클래스 기초: 파이썬 객체지향 프로그래밍에 필수적인 요소 소개
* 파이썬 데이터 모델: 중요 요소 및 각 메서드의 역할

## 6.1 파이썬 객체 소개
앞 장에서 살펴본 몇 가지 표준 파이썬 객체를 객체지향 프로그래밍의 관점에서 살펴보는 것부터 시작하겠습니다.
### 6.1.1 정수형
우선 가장 단순한 정수형 객체를 살펴보죠. 이렇게 간단한 파이썬 객체에도 객체지향 프로그래밍 원리가 존재합니다.

In [1]:
n = 5 # 신규 객체 생성
type(n) # 객체의 자료형

int

In [2]:
n.numerator # 객체의 속성

5

In [3]:
n.bit_length() # 객체의 메서드

3

In [4]:
n + n # + 연산자 적용

10

In [5]:
2 * n # * 연산자 적용

10

In [6]:
n.__sizeof__() # 사용된 메모리 바이트 수를 반환하는 특수 메서드 __sizeof__() 호출

28

> 파이썬의 특수 속성과 특수 메서드는 두 개의 언더바(밑줄, underscore)가 앞뒤에 있습니다. 예로 든 `n.__sizeof__()`는 내부적으로 `import sys; sys.getsizeof(n)` 명령을 수행합니다.

### 6.1.2 리스트

In [7]:
l = [1, 2, 3, 4]
type(l)

list

In [8]:
l[0] # 인덱싱으로 원소 선택

1

In [9]:
l.append(10) # 객체의 메서드

In [10]:
l + l # + 연산자 적용

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [11]:
2 * l # * 연산자 적용

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [12]:
sum(l) # 표준 파이썬 함수 sum() 적용

20

In [13]:
l.__sizeof__() # 특수 메서드 호출

104

### 6.1.3 ndarray
정수와 리스트 객체는 표준 파이썬 객체입니다. 하지만 넘파이의 `ndarray` 객체는 오픈소스 패키지에서 맞춤형 객체입니다.

In [14]:
import numpy as np

In [15]:
a = np.arange(16).reshape((4, 4)) # 신규 객체 생성

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
type(a) # 객체의 자료형

numpy.ndarray

`ndarray` 객체는 표준 객체가 아니지만 이 장의 뒷부분에서 설명할 파이썬 데이터 모델 덕분에 대부분의 경우 마치 표준 객체처럼 동작합니다.

In [18]:
a.nbytes # 객체의 속성

64

In [19]:
a.sum() # 객체의 메서드 (집계)

120

In [20]:
a.cumsum(axis=0) # 객체의 메서드 (집계 없음)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [21]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [22]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [23]:
sum(a) # 표준 파이썬 함수 sum() 적용

array([24, 28, 32, 36])

In [24]:
np.sum(a) # 넘파이 유니버설 함수 np.sum() 적용

120

In [25]:
a.__sizeof__() # 특수 메서드 호출

120

### 6.1.4 DataFrame
마지막으로 `ndarray`와 유사하게 작동하는 판다스의 `DataFrame` 객체를 살펴보겠습니다. 먼저 `ndarray` 객체를 기반으로 `DataFrame` 객체를 만듭니다.

In [26]:
import pandas as pd

In [27]:
df = pd.DataFrame(a, columns=list('abcd'))
type(df)

pandas.core.frame.DataFrame

In [28]:
df.columns # 객체의 속성

Index(['a', 'b', 'c', 'd'], dtype='object')

In [29]:
df.sum() # 객체의 메서드 (집계)

a    24
b    28
c    32
d    36
dtype: int64

In [30]:
df.cumsum() # 객체의 메서드 (집계 없음)

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [31]:
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [32]:
2 * df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [33]:
np.sum(df) # 넘파이 유니버설 함수 np.sum() 적용

a    24
b    28
c    32
d    36
dtype: int64

In [34]:
df.__sizeof__() # 특수 메서드 호출

192

## 6.2 파이썬 클래스 기초
이 절은 파이썬에서 객체지향 프로그래밍을 하기 위한 중요 개념과 구체적인 문법을 다룹니다. 기존 파이썬 자료형으로는 쉽고 효율적인 모델링이 어려운 객체 자료형을 모델링하기 위해 맞춤형 클래스를 만들 것입니다. 이 과정에서 금융 상품을 예로 듭니다. 다음 두 줄의 코드로 새로운 파이썬 클래스를 만들 수 있습니다.

In [35]:
class FinancialInstrument(object): # 클래스 정의
    pass # 이 위치에 구체적인 코드가 옵니다. 아직 아무것도 없기 때문에 pass 키워드만 넣어놨습니다.

In [36]:
fi = FinancialInstrument() # 신규 객체 생성

In [37]:
type(fi) # 객체의 자료형

__main__.FinancialInstrument

In [38]:
fi # 문자열 표현을 반환하는 특수 메서드

In [39]:
fi.__str__() # 문자열 표현을 반환하는 특수 메서드

'<__main__.FinancialInstrument object at 0x000001D6784A5820>'

In [40]:
fi.price = 100 # 일반 속성이 아닌, 이른바 데이터 속성을 객체에서 바로 정의할 수 있습니다.

In [41]:
fi.price

100

중요한 특수 메서드 중 하나는 `__init__`으로 객체의 초기화 시점에 호출됩니다. 이 메서드는 객체 자체를 `self`라는 이름의 인수로 받습니다. 이외에도 다른 인수를 받을 수 있습니다.

In [42]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch' # 클래스의 속성 정의 (모든 객체가 상속받습니다)
    def __init__(self, symbol, price): # 특수 메서드 정의
        # 객체의 속성 정의 (객체마다 개별적인 값을 갖습니다)
        self.symbol = symbol
        self.price = price

In [43]:
FinancialInstrument.author

'Yves Hilpisch'

In [44]:
aapl = FinancialInstrument('AAPL', 100) # 신규 객체 aapl 생성

In [45]:
aapl.symbol # 객체의 속성

'AAPL'

In [46]:
aapl.author # 클래스의 속성

'Yves Hilpisch'

In [47]:
aapl.price = 105 # 객체의 속성값을 바꿉니다
aapl.price

105

금융 상품의 가격은 정기적으로 바뀌지만 금융 상품의 기호는 바뀌지 않습니다. 클래스 정의에서 캡슐화를 도입하기 위해 `get_price()`와 `set_price()`라는 두 개의 메서드를 추가하겠습니다. 다음 코드는 이전의 클래스 정의로부터 상속받습니다.

In [48]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    
    def set_price(self, price):
        self.price = price # 인수로 객체 속성을 업데이트

In [49]:
fi = FinancialInstrument('AAPL', 100)

In [50]:
fi.get_price()

100

In [51]:
fi.set_price(105)

In [52]:
fi.get_price()

105

In [53]:
fi.price

105

캡슐화는 데이터를 사용자로부터 숨기기 위한 것입니다. 이를 위해 `getter/setter` 메서드를 추가합니다. 하지만 사용자가 직접 속성에 접근하여 조작하는 것을 막을 수는 없습니다. 이 때는 프라이빗(private) 속성을 사용해야 합니다. 프라이빗 속성의 이름은 두 개의 밑줄로 시작합니다.

In [54]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price
    
    def get_price(self):
        return self.__price
    
    def set_price(self, price):
        self.__price = price

In [55]:
fi = FinancialInstrument('AAPL', 100)

In [56]:
fi.get_price()

100

In [57]:
fi.__price # 속성에 접근하려고 하면 오류가 발생합니다.

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [58]:
fi._FinancialInstrument__price # 클래스 이름 앞에 밑줄을 붙이고 이 문자열을 속성 이름 앞에 붙이면 속성에 직접 접근할 수 있습니다.

100

In [59]:
fi._FinancialInstrument__price = 105

In [60]:
fi.set_price(100) # 가격을 원래 값으로 되돌립니다.

> **CAUTION**_ 파이썬에서의 캡슐화  
파이썬 클래스에서도 프라이빗 속성과 이 속성을 다루는 메서드를 사용하여 캡슐화를 구현하는 것이 가능하지만 사용자가 절대로 접근할 수 없게 숨길 수는 없습니다. 이는 기술적 특징이라기보다는 공학적인 원리에 가깝습니다.

금융 상품의 포트폴리오 비중을 모델링하는 다른 클래스를 생각해보겠습니다. 두 개의 클래스를 집합화함으로써 이를 구현할 수 있습니다. `PortfolioPosition` 객체는 `FinancialInstrument` 객체를 속성값으로 사용합니다. 여기에 `position_size` 속성을 추가하면 포지션 값을 계산할 수 있습니다.

In [61]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument # FinancialInstrument 객체를 사용하는 속성
        self.__position_size = position_size # PortfolioPosition 클래스의 프라이빗 속성
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
            self.position.get_price() # 속성값에 기반하여 포지션 값 계산

In [62]:
pp = PortfolioPosition(fi, 10)

In [63]:
pp.get_position_size()

10

In [64]:
pp.position.get_price() # 객체 속성을 통해 호출 가능한 함수를 바로 사용할 수 있습니다.

100

In [65]:
pp.position.set_price(105) # 금융 상품의 가격 업데이트

In [66]:
pp.get_position_value() # 업데이트된 가격에 기반하여 포지션 값 새로 계산

1050

## 6.3 파이썬 데이터 모델
앞 절의 예제는 이른바 파이썬 데이터 모델 혹은 객체 모델(https://docs.python.org/3/reference/datamodel.html)의 몇 가지 특성을 보여주었습니다. 파이썬 데이터 모델을 사용하면 기초적인 파이썬 언어로 상호작용할 수 있는 클래스를 설계할 수 있습니다. 파이썬 데이터 모델은 다음과 같은 작업을 지원해야 합니다(Ramalho (2015). p.4 참조).  
* 반복
* 컬렉션 다루기
* 속성 접근
* 연산자 오버로딩
* 함수와 메서드 호출
* 객체 생성과 제거
* 출력을 위한 문자 표현
* 콘텍스트

파이썬 데이터 모델은 아주 중요하므로 이 절에서는 파이썬 데이터 모델의 여러 가지 측면을 다루기로 합니다. Ramalho(2015)의 예제를 조금 변형해서 사용해보죠. 이 예제는 3개의 원소를 가지는 유클리드 공간상의 `Vector` 클래스입니다. 우선 `__init__` 특수 메서드를 살펴봅시다.

In [67]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0): # 3개의 객체 속성(3차원 벡터)
        self.x = x
        self.y = y
        self.z = z

In [68]:
v = Vector(1, 2, 3) # 신규 객체 v 생성

In [69]:
v # 디폴트 문자열 표현

특수 메서드 `__repr__`는 맞춤형 문자열 표현을 정의할 수 있습니다.

In [70]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [71]:
v = Vector(1, 2, 3)

In [72]:
v # 새로운 문자열 표현

Vector(1, 2, 3)

In [73]:
print(v)

Vector(1, 2, 3)


`abs()`와 `bool()`은 표준 파이썬 함수입니다. `Vector` 클래스의 동작을 특수 메서드 `__abs__`와 `__bool__`로 정의합니다.

In [74]:
class Vector(Vector):
    def __abs__(self):
        # 3개의 속성에 기반하여 유클리드 놈(norm)을 계산합니다.
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
    def __bool__(self):
        return bool(abs(self))

In [75]:
v = Vector(1, 2, -1)

In [76]:
abs(v)

2.449489742783178

In [77]:
bool(v)

True

In [78]:
v = Vector()

In [79]:
v

Vector(0, 0, 0)

In [80]:
abs(v)

0.0

In [81]:
bool(v)

False

`+` 연산자와 `*` 연산자는 대부분의 파이썬 객체에 적용할 수 있습니다. 이때의 동작은 특수 메서드 `__add__`와 `__mul__`로 정의합니다.

In [82]:
class Vector(Vector):
    # 각각의 특수 메서드가 해당 클래스 객체를 반환합니다.
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    def __mul__(self, scalar):
        return Vector(self.x*scalar, self.y*scalar, self.z*scalar)

In [83]:
v = Vector(1, 2, 3)

In [84]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [85]:
v * 2

Vector(2, 4, 6)

또다른 표준 파이썬 함수 `len()`은 객체에 포함된 원소의 개수를 반환합니다. 이 함수를 호출하면 객체의 특수 메서드 `__len__`을 사용할 수 있습니다. 특수 메서드 `__getitem__`은 대괄호 기호를 사용하여 원소를 인덱싱할 수 있게 합니다.

In [86]:
class Vector(Vector):
    def __len__(self):
        return 3 # Vector 클래스의 모든 객체 크기는 3입니다.
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [87]:
v = Vector(1, 2, 3)

In [88]:
len(v)

3

In [89]:
v[0]

1

In [90]:
v[-2]

2

In [91]:
v[3]

IndexError: Index out of range.

마지막으로 특수 메서드 `__iter__`는 객체의 원소마다 반복하는 동작을 정의합니다. 이 연산이 정의된 객체는 반복 가능(iterable) 객체라고 합니다. 모든 컬렉션과 컨테이너는 반복 가능합니다.

In [92]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [93]:
v = Vector(1, 2, 3)

In [94]:
for i in range(3): # 인덱스와 __getitem__을 사용한 간접 반복
    print(v[i])

1
2
3


In [95]:
for coordinate in v: # 클래스 객체와 __iter__를 사용한 직접 반복
    print(coordinate)

1
2
3


> **TIP** 파이썬 기능 강화하기  
파이썬 데이터 모델을 사용하면 표준 파이썬 연산, 함수 등과 부드럽게 연결되는 클래스를 정의할 수 있습니다. 이처럼 파이썬은 새로운 클래스와 객체 자료형으로 자신을 강화할 수 있는 유연한 프로그래밍 언어입니다.

그럼 다음 절에서 지금까지의 `Vector` 클래스를 하나의 코드 블록으로 요약하겠습니다.

## 6.4 Vector 클래스

In [97]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x**2 + self.y**2 + self.z**2) ** 0.5
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    def __mul__(self, scalar):
        return Vector(self.x*scalar, self.y*scalar, self.z*scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
        
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

## 6.5 마치며
이번 장에서는 객체지향 프로그래밍의 개념과 방법을 이론과 파이썬 예제를 통해 소개했습니다. 객체지향 프로그래밍은 파이썬의 주된 프로그래밍 패러다임입니다. 이것은 복잡한 애플리케이션의 설계와 구현을 가능하게 하고, 유연한 파이썬 데이터 모델은 표준 파이썬 객체처럼 동작하는 맞춤형 객체를 만들 수 있게 해 줍니다. 객체지향 프로그래밍이 파이썬 프로그래머와 퀀트에게 강력한 도구가 된다는 것은 확실합니다. 객체지향 프로그래밍은 5부에서 개발할 파생상품 가격 결정 패키지의 복잡성과 추상화 요구조건을 해결하는 유일한 프로그래밍 패러다임입니다.